#!/bin/bash

set -x
set +e

TYPO3_BASE_VERSION=12

## Load Environment from .env File
loadEnv() {
  if [ -f ${BASH_SOURCE%/*}/.env.${TYPO3_BASE_VERSION} ]; then
    source "${BASH_SOURCE%/*}/.env.${TYPO3_BASE_VERSION}"
  fi
}

## Create Project Directory
createDirectory() {
  mkdir -p ${PROJECT_NAME}
  cd ${PROJECT_NAME} || exit
}

## Setup ddev
setupDDEV() {
  ddev config \
    --project-name=${PROJECT_NAME} \
    --webserver-type=apache-fpm \
    --php-version=${PHP_VERSION} \
    --database=${DATABASE_VERSION} \
    --project-type=typo3 \
    --docroot=public \
    --web-environment="TYPO3_CONTEXT=Development" \
    --disable-settings-management=false

  ddev config --web-environment-add="COMPOSER_ROOT_VERSION=${COMPOSER_ROOT_VERSION}"
}

## install TYPO3
installTYPO3() {
  ddev start
  rm -f .DS_Store
  ddev composer create --yes --no-interaction typo3/cms-base-distribution:"^${TYPO3_VERSION}"

  ddev composer config --no-interaction --unset platform

  ## better Structure v11
  if [ ${TYPO3_BASE_VERSION} -eq 11 ]; then
    echo 'Change cms-composer-installers for TYPO3 11'
    ddev composer config allow-plugins.typo3/cms-composer-installers true
    ddev composer require --no-interaction "typo3/cms-composer-installers:^4.0@rc"

    echo 'Update for typo3-console'
    ddev exec "sed -i 's/typo3cms install:fixfolderstructure/typo3 install:fixfolderstructure/g' composer.json"
  fi

  ddev composer require --no-interaction "helhum/typo3-console:^${TYPO3_CONSOLE_VERSION}"
}

## Setup TYPO3
setupTYPO3() {
  ddev ${TYPO3_CLI_COMMAND} install:setup \
    --no-interaction \
    --admin-user-name=${TYPO3_USERNAME} \
    --admin-password=${TYPO3_PASSWORD} \
    --use-existing-database \
    --web-server-config=apache \
    --site-name="TYPO3 ${TYPO3_BASE_VERSION}"
}

## Installs necessary packages if INSTALL_INTRODUCTION_PACKAGE is set to 1
installIntroductionPackage() {
  ## Install Introduction Package
  if [ ${INSTALL_INTRODUCTION_PACKAGE} -eq 1 ]; then
    ddev composer require "typo3/cms-introduction:^${INTRODUCTION_VERSION}"
    ddev ${TYPO3_CLI_COMMAND} install:extensionsetupifpossible
    ddev composer remove typo3/cms-introduction

    ## Reinstall Extensions
    ddev composer require "bk2k/bootstrap-package:^${BOOTSTRAP_PACKAGE_VERSION}"
    ddev composer require "b13/container:^${CONTAINER_VERSION}"
    ddev composer require "typo3/cms-indexed-search:^${TYPO3_VERSION}"
  fi
}

## Complete TYPO3 sysexts
getAdditionalModules() {
  ddev composer require "typo3/cms-adminpanel:^${TYPO3_VERSION}"
  ddev composer require "typo3/cms-filemetadata:^${TYPO3_VERSION}"
  ddev composer require "typo3/cms-linkvalidator:^${TYPO3_VERSION}"
  ddev composer require "typo3/cms-lowlevel:^${TYPO3_VERSION}"
  ddev composer require "typo3/cms-opendocs:^${TYPO3_VERSION}"
  ddev composer require "typo3/cms-recycler:^${TYPO3_VERSION}"
  ddev composer require "typo3/cms-redirects:^${TYPO3_VERSION}"
  ddev composer require "typo3/cms-reports:^${TYPO3_VERSION}"
  ddev composer require "typo3/cms-scheduler:^${TYPO3_VERSION}"
}

## Clean System
upgradeSystem() {
  ddev composer update

  ddev ${TYPO3_CLI_COMMAND} install:fixfolderstructure -nq
  ddev ${TYPO3_CLI_COMMAND} database:updateschema -nq
  ddev ${TYPO3_CLI_COMMAND} install:extensionsetupifpossible -nq
  if [ ${TYPO3_BASE_VERSION} -eq 10 ]; then
    ddev typo3 upgrade:run -nq
    ddev ${TYPO3_CLI_COMMAND} cache:flush -nq
  else
    ddev ${TYPO3_CLI_COMMAND} upgrade:run -nq
    ddev ${TYPO3_CLI_COMMAND} cache:flush -nq
    ddev ${TYPO3_CLI_COMMAND} cache:warmup -nq
  fi
}

showStatus() {
  ddev status
}

## delete Project
deleteProject() {
  cd ${PROJECT_NAME} || exit
  ddev delete --omit-snapshot --yes
  cd ..
  rm -rf ${PROJECT_NAME}
}

case "$1" in
install)
  TYPO3_BASE_VERSION=$2
  loadEnv
  createDirectory
  setupDDEV
  installTYPO3
  setupTYPO3
  installIntroductionPackage
  getAdditionalModules
  upgradeSystem
  showStatus
  ;;
delete)
  TYPO3_BASE_VERSION=$2
  loadEnv
  deleteProject
  ;;
*)
  echo 'install | delete'
  ;;
esac
